###########################################################
# Author: Christos Faloutsos
# Date: Feb. 2016
# Usage: 
#	make
#    should create everything you need for this question
###########################################################

hw3:
	python q2.py

clean:

spotless: clean
